/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslatorGuideRouteImport } from './routes/translator-guide'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NinjaSymbolsRouteImport } from './routes/ninja-symbols'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LearningResourcesRouteImport } from './routes/learning-resources'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as KujiInHandSignsRouteImport } from './routes/kuji-in-hand-signs'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CommonMistakesRouteImport } from './routes/common-mistakes'
import { Route as BansenshukaiHistoryRouteImport } from './routes/bansenshukai-history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TranslatorGuideRoute = TranslatorGuideRouteImport.update({
  id: '/translator-guide',
  path: '/translator-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NinjaSymbolsRoute = NinjaSymbolsRouteImport.update({
  id: '/ninja-symbols',
  path: '/ninja-symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningResourcesRoute = LearningResourcesRouteImport.update({
  id: '/learning-resources',
  path: '/learning-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const KujiInHandSignsRoute = KujiInHandSignsRouteImport.update({
  id: '/kuji-in-hand-signs',
  path: '/kuji-in-hand-signs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonMistakesRoute = CommonMistakesRouteImport.update({
  id: '/common-mistakes',
  path: '/common-mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const BansenshukaiHistoryRoute = BansenshukaiHistoryRouteImport.update({
  id: '/bansenshukai-history',
  path: '/bansenshukai-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bansenshukai-history': typeof BansenshukaiHistoryRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/kuji-in-hand-signs': typeof KujiInHandSignsRoute
  '/learn': typeof LearnRoute
  '/learning-resources': typeof LearningResourcesRoute
  '/mcp': typeof McpRoute
  '/ninja-symbols': typeof NinjaSymbolsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/translator-guide': typeof TranslatorGuideRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bansenshukai-history': typeof BansenshukaiHistoryRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/kuji-in-hand-signs': typeof KujiInHandSignsRoute
  '/learn': typeof LearnRoute
  '/learning-resources': typeof LearningResourcesRoute
  '/mcp': typeof McpRoute
  '/ninja-symbols': typeof NinjaSymbolsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/translator-guide': typeof TranslatorGuideRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bansenshukai-history': typeof BansenshukaiHistoryRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/explore': typeof ExploreRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/kuji-in-hand-signs': typeof KujiInHandSignsRoute
  '/learn': typeof LearnRoute
  '/learning-resources': typeof LearningResourcesRoute
  '/mcp': typeof McpRoute
  '/ninja-symbols': typeof NinjaSymbolsRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/translator-guide': typeof TranslatorGuideRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bansenshukai-history'
    | '/common-mistakes'
    | '/explore'
    | '/faq'
    | '/imprint'
    | '/kuji-in-hand-signs'
    | '/learn'
    | '/learning-resources'
    | '/mcp'
    | '/ninja-symbols'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/translator-guide'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bansenshukai-history'
    | '/common-mistakes'
    | '/explore'
    | '/faq'
    | '/imprint'
    | '/kuji-in-hand-signs'
    | '/learn'
    | '/learning-resources'
    | '/mcp'
    | '/ninja-symbols'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/translator-guide'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/bansenshukai-history'
    | '/common-mistakes'
    | '/explore'
    | '/faq'
    | '/imprint'
    | '/kuji-in-hand-signs'
    | '/learn'
    | '/learning-resources'
    | '/mcp'
    | '/ninja-symbols'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/translator-guide'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BansenshukaiHistoryRoute: typeof BansenshukaiHistoryRoute
  CommonMistakesRoute: typeof CommonMistakesRoute
  ExploreRoute: typeof ExploreRoute
  FaqRoute: typeof FaqRoute
  ImprintRoute: typeof ImprintRoute
  KujiInHandSignsRoute: typeof KujiInHandSignsRoute
  LearnRoute: typeof LearnRoute
  LearningResourcesRoute: typeof LearningResourcesRoute
  McpRoute: typeof McpRoute
  NinjaSymbolsRoute: typeof NinjaSymbolsRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TranslatorGuideRoute: typeof TranslatorGuideRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translator-guide': {
      id: '/translator-guide'
      path: '/translator-guide'
      fullPath: '/translator-guide'
      preLoaderRoute: typeof TranslatorGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ninja-symbols': {
      id: '/ninja-symbols'
      path: '/ninja-symbols'
      fullPath: '/ninja-symbols'
      preLoaderRoute: typeof NinjaSymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-resources': {
      id: '/learning-resources'
      path: '/learning-resources'
      fullPath: '/learning-resources'
      preLoaderRoute: typeof LearningResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuji-in-hand-signs': {
      id: '/kuji-in-hand-signs'
      path: '/kuji-in-hand-signs'
      fullPath: '/kuji-in-hand-signs'
      preLoaderRoute: typeof KujiInHandSignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-mistakes': {
      id: '/common-mistakes'
      path: '/common-mistakes'
      fullPath: '/common-mistakes'
      preLoaderRoute: typeof CommonMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bansenshukai-history': {
      id: '/bansenshukai-history'
      path: '/bansenshukai-history'
      fullPath: '/bansenshukai-history'
      preLoaderRoute: typeof BansenshukaiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BansenshukaiHistoryRoute: BansenshukaiHistoryRoute,
  CommonMistakesRoute: CommonMistakesRoute,
  ExploreRoute: ExploreRoute,
  FaqRoute: FaqRoute,
  ImprintRoute: ImprintRoute,
  KujiInHandSignsRoute: KujiInHandSignsRoute,
  LearnRoute: LearnRoute,
  LearningResourcesRoute: LearningResourcesRoute,
  McpRoute: McpRoute,
  NinjaSymbolsRoute: NinjaSymbolsRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TranslatorGuideRoute: TranslatorGuideRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
